cosmetic-settings:
  require-empty-helmet: false
  require-empty-off-hand: true
  require-empty-chest-plate: true
  require-empty-pants: true
  require-empty-boots: true

  # The pitch the player must look down for the backpack to be removed
  # Set to -1 for no removal
  look-down-backpack-remove: 70

  # view distance in blocks that other players will see the backpack cosmetic
  # setting this to lower than the server player view distance should fix the
  # bug where players see random backpacks
  view-distance: 32
wardrobe:
  # if true, the wardrobe will be removed when the player is damaged
  disable-on-damage: true
  # removed if player leaves this radius, set to -1 for infinite radius
  display-radius: -1
  # if the player can use the wardrobe in other locations
  portable: false
  # if the wardrobe should always be displayed in the location below
  always-display: false
  # spawn static wardrobe if in this radius of wardrobe-location
  static-radius: 10
  # how much yaw should change per tick, set to 0 for none
  rotation-speed: 3
  # location of static wardrobe, remove for none
  wardrobe-location:
    world: "World"
    x: 0
    y: 0
    z: 0
    yaw: 0
    pitch: 0
  viewer-location:
    world: "World"
    x: 5
    y: 0
    z: 5
    yaw: 0
    pitch: 0